name: Auto Tag

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'

permissions:
  contents: write

jobs:
  auto-tag:
    name: Create Tag from Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from Cargo.toml
      id: version
      run: |
        VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
        echo "version=v${VERSION}" >> $GITHUB_OUTPUT
        echo "version_number=${VERSION}" >> $GITHUB_OUTPUT

    - name: Check if tag exists
      id: tag_check
      run: |
        if git rev-parse "${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create and push tag
      if: steps.tag_check.outputs.exists == 'false'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
        git push origin "${{ steps.version.outputs.version }}"

    - name: Tag already exists
      if: steps.tag_check.outputs.exists == 'true'
      run: |
        echo "Tag ${{ steps.version.outputs.version }} already exists, skipping..." 